### ISSUE TITLE
Deep Combinator is deprecated

### ISSUE THREAD

**Issue by westside11** [patiek/GoMusPlaylistExport#1]
Hi - thanks for pulling this together.  I'm getting a "/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details." error when I try to run this.  Am I doing something wrong?

Thanks!

**Comment by patiek** [comment]
Code has been updated to use new css content class that google music is now using.

The problem was not as much related to the deep combinator (looks like Google Music is serving up ads using this?) but rather the new content class. Anyway, it should be working again.

**Comment by westside11** [comment]
I can confirm that it's fixed from my end. Thanks so much!
